name: dptta
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.3
  - pytorch=1.10.0
  - torchvision=0.11.0
  - torchaudio=0.10.0
  - numpy
  - scipy
  - pandas
  - tqdm
  - openpyxl
  - matplotlib
  - jupyter
  - pip
  - pip:
      - scikit-learn
      - h5py
